### ISSUE TITLE
Need official bootloader unlocking method for xt

### ISSUE THREAD

**Issue by improbir** [realme-kernel-opensource/realmeXT-kernel-source#1]
There's no official bootloader unlocking method for XT.

**Comment by realme-kernel-opensource** [comment]
font{
        line-height: 1.7;
    }


    

maybe this several days. soon.                



    On 10/14/2019 22:05，iampro<notifications@github.com> wrote： 


There's no official bootloader unlocking method for XT.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.


        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }

**Comment by thesprintster** [comment]
close it now @improbir 
BTW nice release @realme-kernel-opensource , i got custom kernel working.

https://github.com/thesprintster/kernel_realme_RMX1921/commits/pie

**Comment by improbir** [comment]
solved
